[package]
name = "splash"
version = "0.1.0"
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
description = "RF Signal Propagation analysis tool: like SPLAT! but more flexible"
license = "Artistic-2.0"

[dependencies]
